version: '3.1'

services:
  db:
    image: postgres
    container_name: springBootPsql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogDB
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: